development:
  adapter: sqlite3
  database: messenger_development
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: messenger_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: messenger_production
  pool: 5
  timeout: 5000